<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Castle.Core" Version="5.1.1" />
		<PackageReference Include="Moq" Version="4.20.70" />
		<PackageReference Include="xunit" Version="2.9.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\NoisEmap.Domain\NoisEmap.Domain.csproj" />
		<ProjectReference Include="..\NoisEmap.Application\NoisEmap.Application.csproj" />
	</ItemGroup>
</Project>